// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXZFXWCSGA6aDasjNJUTiENBAo71emmg',
    appId: '1:1087776430753:web:c50fc87a4ad52f319e2ee0',
    messagingSenderId: '1087776430753',
    projectId: 'welfare-firebase',
    authDomain: 'welfare-firebase.firebaseapp.com',
    storageBucket: 'welfare-firebase.appspot.com',
    measurementId: 'G-XGLELDPVXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUgsbcY-mLAVLicQP5QmJf3GfFtbKTpA',
    appId: '1:1087776430753:android:44c111118ecd60619e2ee0',
    messagingSenderId: '1087776430753',
    projectId: 'welfare-firebase',
    storageBucket: 'welfare-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaprMXk2XIC_yVHYsYQ9asu6H67wJrGRc',
    appId: '1:1087776430753:ios:a4bed40ce0df45a59e2ee0',
    messagingSenderId: '1087776430753',
    projectId: 'welfare-firebase',
    storageBucket: 'welfare-firebase.appspot.com',
    iosBundleId: 'com.example.welfareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaprMXk2XIC_yVHYsYQ9asu6H67wJrGRc',
    appId: '1:1087776430753:ios:a1b8d2d4581783a79e2ee0',
    messagingSenderId: '1087776430753',
    projectId: 'welfare-firebase',
    storageBucket: 'welfare-firebase.appspot.com',
    iosBundleId: 'com.example.welfareApp.RunnerTests',
  );
}
